name: 'Restore Node'
description: 'Setup node and restore node_modules'

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: https://registry.npmjs.org/
    - name: Restore node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
