name: Deploy website

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build website
      run: |
        npm install
        npx nx build website

    - name: Deploy to Azure
      uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
      with:
        source-path: dist/apps/website
        sas-url: ${{ secrets.DEPLOY_SAS_URL }}
        container: roots-dev
