name: Roots Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  reduncy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  setup:
    runs-on: ubuntu-18.04
    steps:
      - name: Roots - Checkout
        uses: actions/checkout@v3
      - name: Setun Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci

  lint-web:
    needs: [setup]
    runs-on: ubuntu-18.04
    steps:
      - name: Roots - Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Web linter
        run: npx nx lint website

  test-web:
    needs: [setup]
    runs-on: ubuntu-18.04
    steps:
      - name: Roots - Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Web tests
        run: npx nx test website

  build-web:
    needs: [setup]
    environment: ${{ github.ref_name != 'main' && 'develop' || 'prod' }}
    runs-on: ubuntu-18.04
    steps:
      - name: Roots - Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Build website
        run: npx nx build website
        env:
          NX_ACCESS_TOKEN: ${{ secrets.NX_ACCESS_TOKEN }}
          NX_SPACE_ID: ${{ secrets.NX_SPACE_ID }}
          NX_ENVIRONMENT: ${{ secrets.NX_ENVIRONMENT }}
      - name: Upload build files
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: dist/app/website

  deploy-web:
    needs: [build-web, lint-web, test-web]
    runs-on: ubuntu-18.04
    environment: ${{ github.ref_name != 'main' && 'develop' || 'prod' }}
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Download build files
        uses: actions/download-artifact@v3
        with:
          name: website
          path: dist
      - name: Deploy in Azure Storage
        uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
        with:
          source-path: dist
          sas-url: ${{ secrets.DEPLOY_SAS_URL }}
          container: ${{ secrets.STORAGE_CONTAINER }}







