name: Roots Pipeline

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize]

jobs:
  reduncy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Roots - Checkout
        uses: actions/checkout@v3
      - name: Setup and cache node_modules
        id: setup-node
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci

  lint-web:
    needs: [setup]
    runs-on: ubuntu-20.04
    steps:
      - name: Symbol - Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        uses: ./.github/actions/restore-node-modules
      - name: Web Linter
        run: npx nx lint website

  build-web:
    needs: [setup]
    environment: ${{ github.ref_name != 'main' && 'develop' || 'production' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Symbol - Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Web
        uses: ./.github/actions/project-builder
        with:
          project: website
        env:
          NX_ACCESS_TOKEN: ${{ secrets.NX_ACCESS_TOKEN }}
          NX_ENVIRONMENT: ${{ secrets.NX_ENVIRONMENT }}
          NX_SPACE_ID: ${{ secrets.NX_SPACE_ID }}
      - name: Upload build files
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: dist/apps/website

  deploy-web:
    needs: [build-web, lint-web]
    runs-on: ubuntu-20.04
    environment: ${{ github.ref_name != 'main' && 'develop' || 'production' }}
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Download build files
        uses: actions/download-artifact@v3
        with:
          name: website
          path: dist
      - name: Deploy in Azure Storage
        uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
        with:
          source-path: dist
          sas-url: ${{ secrets.DEPLOY_SAS_URL }}
          container: ${{ secrets.STORAGE_CONTAINER }}
